// quota-checker.js (mini)
const CFG_DEFAULT = { budgets:{search_tokens_per_day:50000, api_credits_per_day:1000, rpm:30, rps:3}, thresholds:{yellow:0.6, red:0.8} };
const todayKey=()=>new Date().toISOString().slice(0,10);
const loadState=()=>{try{const s=JSON.parse(localStorage.getItem('qg.state')||'null');return(s&&s.day===todayKey())?s:{day:todayKey(),tokens:0,credits:0,events:[]};}catch{return{day:todayKey(),tokens:0,credits:0,events:[]}}};
const saveState=s=>{try{localStorage.setItem('qg.state',JSON.stringify(s));}catch{}};
const prune=ev=>{const now=Date.now(),m=now-60000,s=now-1000;const recent=ev.filter(t=>t>=m);return{recent,rpm:recent.length,rps:recent.filter(t=>t>=s).length}};
const banner=(()=>{const b=document.createElement('div');Object.assign(b.style,{position:'fixed',top:'0',left:'0',right:'0',zIndex:'9999',display:'none',padding:'8px 12px',textAlign:'center',font:'14px system-ui,-apple-system,Segoe UI,Roboto,Arial'});document.addEventListener('DOMContentLoaded',()=>document.body.appendChild(b));return(lvl,msg)=>{if(lvl==='none'){b.style.display='none';return;}b.style.display='block';b.style.background=lvl==='yellow'?'#ffcf70':'#ff8a8a';b.style.color='#0b0e13';b.textContent=msg;};})();
async function fetchCfg(){try{const r=await fetch('quota.guardian.json',{cache:'no-store'});if(!r.ok)throw 0;const c=await r.json();return{...CFG_DEFAULT,...c};}catch{return CFG_DEFAULT;}}
const QuotaGuardian=(()=>{let cfg=CFG_DEFAULT,state=loadState();const ready=(async()=>{cfg=await fetchCfg();})();function status(){if(state.day!==todayKey()){state={day:todayKey(),tokens:0,credits:0,events:[]};saveState(state);}const pr=prune(state.events);state.events=pr.recent;const pTok=cfg.budgets.search_tokens_per_day?state.tokens/cfg.budgets.search_tokens_per_day:0;const pCre=cfg.budgets.api_credits_per_day?state.credits/cfg.budgets.api_credits_per_day:0;const lvlRate=(pr.rpm>=cfg.budgets.rpm||pr.rps>=cfg.budgets.rps)?'red':(pr.rpm>=cfg.budgets.rpm*cfg.thresholds.yellow||pr.rps>=cfg.budgets.rps*cfg.thresholds.yellow)?'yellow':'none';const lvlTok=pTok>=cfg.thresholds.red?'red':pTok>=cfg.thresholds.yellow?'yellow':'none';const lvlCre=pCre>=cfg.thresholds.red?'red':pCre>=cfg.thresholds.yellow?'yellow':'none';const level=['red','yellow','none'].find(L=>[lvlTok,lvlCre,lvlRate].includes(L))||'none';return{level,pTok,pCre,rpm:pr.rpm,rps:pr.rps}}function show(){const s=status();if(s.level==='red')banner('red','Budget limit reached. New searches paused.');else if(s.level==='yellow')banner('yellow','Approaching daily/rate budget. Slow down.');else banner('none');}function guard({tokens=0,credits=0}={}){const pr=prune([...state.events,Date.now()]);const pTok=(state.tokens+tokens)/cfg.budgets.search_tokens_per_day,pCre=(state.credits+credits)/cfg.budgets.api_credits_per_day;const red=pTok>=cfg.thresholds.red||pCre>=cfg.thresholds.red||pr.rpm>cfg.budgets.rpm||pr.rps>cfg.budgets.rps;if(red){banner('red','Budget limit reached.');return false;}const yellow=pTok>=cfg.thresholds.yellow||pCre>=cfg.thresholds.yellow||pr.rpm>=cfg.budgets.rpm*cfg.thresholds.yellow||pr.rps>=cfg.budgets.rps*cfg.thresholds.yellow;if(yellow)banner('yellow','Approaching daily/rate budget.');else banner('none');return true;}function record({tokens=0,credits=0}={}){state.events.push(Date.now());state.tokens+=tokens;state.credits+=credits;saveState(state);show();}function resetToday(){state={day:todayKey(),tokens:0,credits:0,events:[]};saveState(state);show();}ready.then(show);return{ready,status,guard,record,resetToday};})();
window.QuotaGuardian=QuotaGuardian; export {};
